# Kyverno Policy: Verify Image Signatures with Cosign
# Enforces that all container images are signed with Sigstore Cosign
# SLSA Level 3 requirement: Provenance verification

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-image-signatures
  annotations:
    policies.kyverno.io/title: Verify Image Signatures
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: critical
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      All container images must be signed using Cosign with keyless signing
      (Fulcio/Rekor). This policy verifies signatures before allowing pod admission.
    compliance.framework/slsa: "Level-3"
    compliance.framework/nist: "SA-15,SI-7"
    compliance.framework/fedramp: "CM-14,SA-12"
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  background: false # Image verification must be done at admission time

  rules:
    - name: verify-signature-keyless
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          # Exclude system namespaces (already verified at deployment)
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease
                - gatekeeper-system
                - kyverno

      verifyImages:
        # Verify all images from allowed registries
        - imageReferences:
            - "*"

          # Keyless verification using Fulcio/Rekor
          attestors:
            - entries:
                - keyless:
                    subject: "*@*" # Email or OIDC subject
                    issuer: "https://token.actions.githubusercontent.com" # GitHub Actions
                    rekor:
                      url: https://rekor.sigstore.dev
                - keyless:
                    subject: "*@*"
                    issuer: "https://sts.windows.net/*" # Azure AD
                    rekor:
                      url: https://rekor.sigstore.dev

          # Require attestations (optional but recommended)
          attestations:
            - predicateType: https://slsa.dev/provenance/v0.2
              attestors:
                - entries:
                    - keyless:
                        subject: "*@*"
                        issuer: "https://token.actions.githubusercontent.com"
                        rekor:
                          url: https://rekor.sigstore.dev

    - name: verify-signature-chainguard
      match:
        any:
          - resources:
              kinds:
                - Pod
      exclude:
        any:
          - resources:
              namespaces:
                - kube-system
                - kube-public
                - kube-node-lease

      verifyImages:
        # Chainguard images have Cosign signatures
        - imageReferences:
            - "cgr.dev/*"
            - "ghcr.io/chainguard-images/*"

          attestors:
            - entries:
                # Chainguard uses keyless signing
                - keyless:
                    subject: "*@chainguard.dev"
                    issuer: "https://token.actions.githubusercontent.com"
                    rekor:
                      url: https://rekor.sigstore.dev

          # Verify SLSA provenance attestation
          attestations:
            - predicateType: https://slsa.dev/provenance/v0.2
              conditions:
                - all:
                    - key: "{{ buildType }}"
                      operator: Equals
                      value: "https://slsa.dev/provenance/v0.2"
