# Local values for reuse across resources

locals {
  # Cluster identity naming
  cluster_identity_name = "${var.cluster_name}-identity"
  kubelet_identity_name = "${var.cluster_name}-kubelet-identity"

  # Node resource group (auto-generated by AKS)
  node_resource_group = "MC_${var.resource_group_name}_${var.cluster_name}_${var.location}"

  # Network configuration
  network_plugin_mode = var.network_plugin == "azure" && var.enable_overlay_networking ? "overlay" : null

  # Determine outbound type based on configuration
  outbound_type = var.use_user_defined_routing ? "userDefinedRouting" : (
    var.enable_nat_gateway ? "userAssignedNATGateway" : "loadBalancer"
  )

  # DNS configuration
  dns_service_ip    = var.dns_service_ip
  service_cidr      = var.service_cidr
  pod_cidr          = var.enable_overlay_networking ? var.pod_cidr : null

  # Tags with compliance metadata
  default_tags = merge(
    var.tags,
    {
      "ManagedBy"           = "Terraform"
      "Cluster"             = var.cluster_name
      "Environment"         = var.environment
      "SecurityBaseline"    = "CIS-Benchmark-v1.8"
      "ComplianceFramework" = "DoD-STIG-v1r12-NIST-800-190-FedRAMP"
      "DataClassification"  = var.data_classification
      "CostCenter"          = var.cost_center
      "CreatedDate"         = timestamp()
    }
  )

  # System node pool configuration
  system_node_pool = {
    name                         = "system"
    vm_size                      = var.system_node_pool_vm_size
    os_disk_size_gb             = var.system_node_pool_os_disk_size
    os_disk_type                = var.system_node_pool_os_disk_type
    os_sku                      = var.node_os_sku
    kubelet_disk_type           = "OS"
    enable_auto_scaling         = true
    min_count                   = var.system_node_pool_min_count
    max_count                   = var.system_node_pool_max_count
    max_pods                    = var.system_node_pool_max_pods
    zones                       = var.availability_zones
    only_critical_addons_enabled = true
    vnet_subnet_id              = var.aks_subnet_id
    pod_subnet_id               = var.enable_overlay_networking ? null : var.aks_pod_subnet_id
    upgrade_settings = {
      max_surge = "33%"
    }
  }

  # Kubelet configuration for all node pools
  kubelet_config = {
    cpu_manager_policy        = "static"
    topology_manager_policy   = "best-effort"
    allowed_unsafe_sysctls    = []
    container_log_max_size_mb = 50
    container_log_max_line    = 5000
    pod_max_pid               = 4096
  }

  # Linux OS configuration for CIS compliance
  linux_os_config = {
    swap_file_size_mb = 0 # CIS 4.1.1 - Disable swap

    sysctl_config = {
      # Network security hardening
      net_ipv4_ip_forward                  = 1  # Required for K8s
      net_ipv4_conf_all_forwarding         = 1
      net_bridge_bridge_nf_call_iptables   = 1
      net_ipv4_tcp_tw_reuse                = true

      # CIS 3.1.1 - Network parameter hardening
      net_ipv4_conf_all_send_redirects     = 0
      net_ipv4_conf_default_send_redirects = 0
      net_ipv4_conf_all_accept_redirects   = 0
      net_ipv4_conf_default_accept_redirects = 0

      # Memory and process limits
      vm_max_map_count   = 262144
      kernel_threads_max = 65536
    }
  }

  # Diagnostic log categories
  diagnostic_log_categories = [
    "kube-apiserver",
    "kube-controller-manager",
    "kube-scheduler",
    "kube-audit",
    "kube-audit-admin",
    "guard",
    "cluster-autoscaler",
    "cloud-controller-manager",
    "csi-azuredisk-controller",
    "csi-azurefile-controller",
    "csi-snapshot-controller",
  ]

  # Metric categories
  diagnostic_metric_categories = [
    "AllMetrics"
  ]

  # RBAC role assignments
  rbac_assignments = {
    network_contributor = {
      role_definition_name = "Network Contributor"
      scope               = var.aks_subnet_id
      principal_id        = azurerm_user_assigned_identity.aks_identity.principal_id
    }
    monitoring_metrics_publisher = {
      role_definition_name = "Monitoring Metrics Publisher"
      scope               = azurerm_kubernetes_cluster.aks.id
      principal_id        = azurerm_user_assigned_identity.aks_identity.principal_id
    }
  }
}
